use std::fs::File;
use std::path::{Path, PathBuf};

use h3o::{LatLng, Resolution};
use memmap2::Mmap;

use crate::engine::error::GeoEngineError;
use crate::spatial_sidecar::{SPATIAL_BACKEND_H3, SPATIAL_BACKEND_S2, SpatialSidecarFile};

#[derive(Debug)]
pub struct SpatialRuntimeIndex {
    mmap: Mmap,
}

impl SpatialRuntimeIndex {
    pub fn from_file(path: &Path) -> Result<Self, GeoEngineError> {
        let file = File::open(path).map_err(|source| GeoEngineError::DatabaseOpen {
            path: path.to_path_buf(),
            source,
        })?;

        let mmap = unsafe { Mmap::map(&file) }.map_err(|source| GeoEngineError::DatabaseMap {
            path: path.to_path_buf(),
            source,
        })?;

        let index = Self { mmap };
        let _ = index.archived();
        Ok(index)
    }

    pub fn candidate_country_ids(&self, lat: f32, lon: f32) -> Option<&rkyv::Archived<Vec<u32>>> {
        let archived = self.archived();
        let cell = point_to_backend_cell(archived.backend.into(), lat, lon, archived.level.into())?;

        let mut lo = 0usize;
        let mut hi = archived.cells.len();
        while lo < hi {
            let mid = (lo + hi) / 2;
            let mid_cell: u64 = archived.cells[mid].cell.into();
            if mid_cell < cell {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if lo < archived.cells.len() {
            let found: u64 = archived.cells[lo].cell.into();
            if found == cell {
                return Some(&archived.cells[lo].country_ids);
            }
        }

        None
    }

    pub fn polygon_candidates(
        &self,
        lat: f32,
        lon: f32,
        allowed_country_ids: Option<&[u32]>,
    ) -> Vec<(u32, u32)> {
        let archived = self.archived();
        let mut out = Vec::new();
        let allowed = allowed_country_ids.unwrap_or(&[]);
        let restrict = !allowed.is_empty();

        for idx in 0..archived.polygon_country_ids.len() {
            let country_id: u32 = archived.polygon_country_ids[idx].into();
            if restrict && !allowed.contains(&country_id) {
                continue;
            }

            let min_lon: f32 = archived.min_lon[idx].into();
            let min_lat: f32 = archived.min_lat[idx].into();
            let max_lon: f32 = archived.max_lon[idx].into();
            let max_lat: f32 = archived.max_lat[idx].into();

            if lon >= min_lon && lon <= max_lon && lat >= min_lat && lat <= max_lat {
                let ring_id: u32 = archived.polygon_ring_ids[idx].into();
                out.push((country_id, ring_id));
            }
        }

        out
    }

    fn archived(&self) -> &rkyv::Archived<SpatialSidecarFile> {
        rkyv::access::<rkyv::Archived<SpatialSidecarFile>, rkyv::rancor::Error>(&self.mmap[..])
            .unwrap_or_else(|_| unsafe {
                // SAFETY: Sidecar file is generated by this project.
                rkyv::access_unchecked(&self.mmap[..])
            })
    }
}

pub fn merge_candidate_ids(
    cell_candidates: Option<&rkyv::Archived<Vec<u32>>>,
    rtree: impl Iterator<Item = u32>,
) -> Vec<u32> {
    let mut out = Vec::new();

    if let Some(ids) = cell_candidates {
        out.reserve(ids.len());
        for id in ids.iter() {
            out.push(id.into());
        }
    }

    for id in rtree {
        if !out.contains(&id) {
            out.push(id);
        }
    }

    out
}

pub fn default_sidecar_path(db_path: &Path) -> PathBuf {
    db_path.with_extension("spx")
}

pub fn point_to_backend_cell(backend: u8, lat: f32, lon: f32, level: u8) -> Option<u64> {
    match backend {
        SPATIAL_BACKEND_H3 => point_to_h3_cell(lat, lon, level),
        SPATIAL_BACKEND_S2 => point_to_s2_cell(lat, lon, level),
        _ => None,
    }
}

fn point_to_h3_cell(lat: f32, lon: f32, level: u8) -> Option<u64> {
    let latlng = LatLng::new(lat as f64, lon as f64).ok()?;
    let res = Resolution::try_from(level).ok()?;
    Some(u64::from(latlng.to_cell(res)))
}

#[cfg(feature = "s2")]
fn point_to_s2_cell(lat: f32, lon: f32, level: u8) -> Option<u64> {
    use s2::cellid::{CellID, MAX_LEVEL};
    use s2::latlng::LatLng;

    let ll = LatLng::from_degrees(lat as f64, lon as f64);
    let level = (level as u64).min(MAX_LEVEL);
    let cell = CellID::from(ll).parent(level);
    Some(cell.0)
}

#[cfg(not(feature = "s2"))]
fn point_to_s2_cell(_lat: f32, _lon: f32, _level: u8) -> Option<u64> {
    None
}
